### ISSUE TITLE
Jitpack Issues ~~Update to Java 16~~

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Shnupbups/Piglib#6]
I was receiving errors trying to get 1.0.3 via jitpack, so I checked piglib on [the jitpack site](https://jitpack.io/#Shnupbups/Piglib/). 
Here's [the log with the error](https://jitpack.io/com/github/Shnupbups/Piglib/1.0.3/build.log) saying 
> You are using an outdated version of Java (8). Java 16 or higher is required.

**Comment by supersaiyansubtlety** [comment]
With 1.0.3a, there's a [new error](https://jitpack.io/com/github/Shnupbups/Piglib/1.0.3a/build.log)
```
java.lang.IllegalArgumentException: Unsupported class file major version 60
```
Sounds like jitpack doesn't like the `a` in `1.0.3a`?

**Comment by triphora** [comment]
Use the Modrinth maven instead if you're still having this issue (I'm assuming you are since the issue isn't closed)
```groovy
dependencies {
  maven { url = "https://api.modrinth.com/maven" }
}

modApi "maven.modrinth:piglib:1.0.3-1.16"
include "maven.modrinth:piglib:1.0.3-1.16"
```
I don't know if there was a 1.0.3 release for 1.17, but if not, that'll still need to be uploaded to Modrinth.

**Comment by supersaiyansubtlety** [comment]
Unfortunately there's no 1.17 full release on either modrinth or curseforge.
